### ISSUE TITLE
You forgot the apk?

### ISSUE THREAD

**Issue by Kman6664230** [fifomori/android#1]
I tried for like half an hour both looking for the apk and trying to build the app with android studio or other apps. The problem is, my phone isn’t compatible with android studio, meaning I can’t build it. I was wondering if u could upload the apk in the repository. I was also wondering if it was necessary for me to put on the steam key…

**Comment by cafeed28** [comment]
You can find apks in the [actions](https://github.com/fifomori/android/actions) artifacts, but I guess I should make a releases

**Comment by Kman6664230** [comment]
> You can find apks in the [actions](https://github.com/fifomori/android/actions) artifacts, but I guess I should make a releases

Please do, I have no idea how to get it, I don’t use GitHub that much :3

**Comment by cafeed28** [comment]
Here is a release: https://github.com/fifomori/android/releases/tag/v1.2.3-beta
