### ISSUE TITLE
when i loading mod Autumnbreak-sc error

### ISSUE THREAD

**Issue by kltu1145** [fifomori/android#10]
when i loading mod Autumnbreak-sc(简体中文版本 and it been unzip) have a error
and when I create a new game it had an error

![Screenshot_20240825_003304_com.cafeed28.omori.jpg](https://github.com/user-attachments/assets/77cc304f-fc23-4ee4-ad82-6d5424a94912)

![Screenshot_20240825_003238_com.cafeed28.omori.jpg](https://github.com/user-attachments/assets/c89bca38-a986-47a3-a6c8-b72d86d3826d)

![omori.txt](https://github.com/user-attachments/files/16737389/omori.txt)

**Comment by cafeed28** [comment]
Autumn break is not supported yet, because it replaces whole .js files instead of patching them

**Comment by kltu1145** [comment]
ok thanks
