### ISSUE TITLE
CEP mods pack

### ISSUE THREAD

**Issue by kltu1145** [fifomori/android#11]
When I installed it in the CEP module(all unzip) package 
 mod save saver  An error occurred
![Screenshot_20240825_135839_com.cafeed28.omori.jpg](https://github.com/user-attachments/assets/4c8737d4-ab34-4bf2-91bf-0e358e3b9aa2)
![omori.txt](https://github.com/user-attachments/files/16739263/omori.txt)

I deleted this mod
But when I entered the game again, smilemore mod did not replace the game image

**Comment by kltu1145** [comment]
![Screenshot_20240825_144811_com.cafeed28.omori.jpg](https://github.com/user-attachments/assets/05228e72-a2fb-4cdc-a7b9-4b280f210ca3)

**Comment by kltu1145** [comment]
i can run it on pc computer
![image](https://github.com/user-attachments/assets/7ec783b2-d440-40cf-8fe7-b89b83b67074)

**Comment by cafeed28** [comment]
looks like this mod is replacing a lot of things, from what i can see it uses modded version of oneloader which can be unsupported

**Comment by kltu1145** [comment]
Thanks a lot
