### ISSUE TITLE
WebAudio.initialize is not a function

### ISSUE THREAD

**Issue by kltu1145** [fifomori/android#16]
![omori(2).txt](https://github.com/user-attachments/files/17243996/omori.2.txt)

![210f6bf2db22e71b.jpg](https://github.com/user-attachments/assets/55eef313-e2df-4639-98f1-b4d08008ac16)

**Comment by kltu1145** [comment]
![omori(2).txt](https://github.com/user-attachments/files/17244012/omori.2.txt)

**Comment by cafeed28** [comment]
🤷‍♂️ i think you're doing something wrong, try running without mods (OneLoader) and/or reinstalling your game
