### ISSUE TITLE
Loading error... HELP

### ISSUE THREAD

**Issue by kyunimo** [fifomori/android#3]
I did everything that was instructed in the installation but I still got this message... Help T T
![Screenshot_20240430-215755.jpg](https://github.com/fifomori/android/assets/115450845/cf5e4176-cf33-4af7-b100-08374fb8816f)

**Comment by cafeed28** [comment]
Please send your debug logs (clear debug logs from main menu, try to load the game again then save debug logs from menu)

**Comment by kyunimo** [comment]
> Please send your debug logs (clear debug logs from main menu, try to load the game again then save debug logs from menu)

Apologies for the delay. I found the log file but I still can't figure out what's wrong T v T
[omori.log](https://github.com/fifomori/android/files/15177569/omori.log)

**Comment by cafeed28** [comment]
Hm, maybe your installation is missing the 'maps' directory. Show the contents of your 'www' folder

**Comment by kyunimo** [comment]
I can't really tell... is there something missing?
![Screenshot_20240501-215722](https://github.com/fifomori/android/assets/115450845/19411794-065f-41d8-8660-95044cfca196)

**Comment by cafeed28** [comment]
It's not missing, then maybe your omori installation is decrypted, that can cause problems like this. You can check it by file extensions (e.g. files in 'data': '.json' = decrypted, '.KEL' = encrypted)

**Comment by kyunimo** [comment]
> ~Hm, maybe your installation is missing the 'maps' directory. Show the contents of your 'www' folder~. Or your omori installation is decrypted, that can cause problems like this.

Oh I see, is there something I can do to make it work? T T

**Comment by cafeed28** [comment]
> Oh I see, is there something I can do to make it work? T T

You can copy original files of omori from Steam, or try to install and enable OneLoader (but I'm not sure if it will help)

**Comment by kyunimo** [comment]
> You can copy original files of omori from Steam, or try to install and enable OneLoader (but I'm not sure if it will help)
Hey! I tried it out with OneLoader enabled like what you said but this message popped up (1st img), I pressed ok then it loaded for a while and it just frozed at 100% (2nd img) it says 25 seconds but i've been waiting longer than that... pls help T T...
![Screenshot_20240501-221116](https://github.com/fifomori/android/assets/115450845/533ee30b-5adf-4213-8df8-38f6e8200139)

**Comment by cafeed28** [comment]
Hm, then I guess you need to use original omori files that's not decrypted

**Comment by kyunimo** [comment]
> Hm, then I guess you need to use original omori files that's not decrypted

Oh, I see T v T... Well then, thanks for helping me out this far. Now I know what I'll do next time
