### ISSUE TITLE
Black Screen crash to Home Screen

### ISSUE THREAD

**Issue by Soloem** [fifomori/android#7]
I've reviewed quite a few of the issues posted here and followed some other information elsewhere and I can't seem to get it to run. It gets stuck on a black screen (which can turn gray if I press a button, using a Retroid Pocket handheld even without controller support). Or just crashes back to the Home Screen.

I'm using the newly release Beta.

I currently have the `www` folder in `storage/emulated/0/OMORI/www` as it seemed the app was having trouble getting it on an SD Card or within too many folders. I have also tried just simply using the `OMORI` directory and the `www` directory.

`www` causes the back to Home Screen crash.
`OMORI` does nothing and stays on a black screen.

`www` Log
[omori.log](https://github.com/user-attachments/files/16470759/omori.log)

`OMORI` Log
[omori.log](https://github.com/user-attachments/files/16470836/omori.log)

The chip is also a Unisoc T618, so it may simply be possible that this won't boot due to that.

**Comment by cafeed28** [comment]
Please run `adb logcat -c` then `adb logcat`, crash the game (with `www` folder set as installation directory) and send the output here

**Comment by Soloem** [comment]
Here's the output:

https://pastebin.com/57JGAp01

**Comment by cafeed28** [comment]
Looks like your webview is crashing, you can try to download Android System WebView Beta from play store and set it as WebView implementation in Developer settings
![image](https://github.com/user-attachments/assets/d5b68658-0614-4f50-a0a4-5541a38abdc7)
![image](https://github.com/user-attachments/assets/d5195d96-50e9-4e12-8049-05b7fe226b0f)

**Comment by Soloem** [comment]
That did indeed fix it. Thanks!
